# Generated by Django 2.1.1 on 2018-11-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20181107_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_time', 'ordering': ['-pub_time'], 'verbose_name': 'text', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'type_name', 'verbose_name_plural': 'type_list'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'tag-name', 'verbose_name_plural': 'tag_list'},
        ),
    ]
