# Generated by Django 2.1.3 on 2019-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='904405840@qq.com', max_length=100, verbose_name='邮件地址'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名'),
        ),
    ]
